nodes = [
    "Kyiv",
    "Vinnytsia",
    "Lutsk",
    "Dnipro",
    "Donetsk",
    "Zhytomyr",
    "Uzhhorod",
    "Zaporizhzhia",
    "Ivano-Frankivsk",
    "Kropyvnytskyi",
    "Luhansk",
    "Lviv",
    "Mykolaiv",
    "Odesa",
    "Poltava",
    "Rivne",
    "Sumy",
    "Ternopil",
    "Kharkiv",
    "Kherson",
    "Khmelnytskyi",
    "Cherkasy",
    "Chernivtsi",
    "Chernihiv",
    "Simferopol",
    "Sevastopol",
]

edges = [
    ("Kyiv", "Zhytomyr", 140),
    ("Kyiv", "Chernihiv", 150),
    ("Kyiv", "Cherkasy", 190),
    ("Kyiv", "Poltava", 340),
    ("Kyiv", "Vinnytsia", 270),
    ("Zhytomyr", "Rivne", 190),
    ("Zhytomyr", "Khmelnytskyi", 190),
    ("Rivne", "Lutsk", 75),
    ("Rivne", "Lviv", 210),
    ("Lviv", "Ternopil", 130),
    ("Lviv", "Ivano-Frankivsk", 135),
    ("Lviv", "Uzhhorod", 260),
    ("Ternopil", "Khmelnytskyi", 110),
    ("Ternopil", "Ivano-Frankivsk", 130),
    ("Ivano-Frankivsk", "Chernivtsi", 135),
    ("Chernivtsi", "Khmelnytskyi", 190),
    ("Vinnytsia", "Khmelnytskyi", 120),
    ("Vinnytsia", "Cherkasy", 260),
    ("Cherkasy", "Kropyvnytskyi", 130),
    ("Kropyvnytskyi", "Dnipro", 245),
    ("Kropyvnytskyi", "Mykolaiv", 200),
    ("Dnipro", "Zaporizhzhia", 85),
    ("Dnipro", "Poltava", 200),
    ("Dnipro", "Kharkiv", 215),
    ("Kharkiv", "Sumy", 180),
    ("Kharkiv", "Luhansk", 340),
    ("Kharkiv", "Donetsk", 310),
    ("Zaporizhzhia", "Donetsk", 230),
    ("Zaporizhzhia", "Kherson", 250),
    ("Kherson", "Mykolaiv", 70),
    ("Mykolaiv", "Odesa", 130),
    ("Odesa", "Vinnytsia", 420),
    ("Kherson", "Simferopol", 300),
    ("Simferopol", "Sevastopol", 80),
]

nodes_positions = {
    "Uzhhorod": (22, 48),
    "Lviv": (24, 49),
    "Lutsk": (25, 51),
    "Rivne": (26, 50),
    "Ternopil": (25, 49),
    "Ivano-Frankivsk": (25, 48),
    "Chernivtsi": (27, 48),
    "Khmelnytskyi": (27, 49),
    "Zhytomyr": (28, 50),
    "Vinnytsia": (28, 49),
    "Kyiv": (30, 50),
    "Chernihiv": (31, 51),
    "Cherkasy": (32, 49),
    "Poltava": (35, 49),
    "Sumy": (35, 51),
    "Kropyvnytskyi": (32, 48),
    "Dnipro": (35, 48),
    "Zaporizhzhia": (36, 47),
    "Kharkiv": (36, 50),
    "Donetsk": (38, 48),
    "Luhansk": (39, 49),
    "Mykolaiv": (32, 47),
    "Kherson": (33, 46),
    "Odesa": (30, 46),
    "Simferopol": (34, 45),
    "Sevastopol": (33, 45),
}
